sudo npm install express
sudo npm install socket.io-handshake
sudo npm install body-parser
sudo npm install mysql
sudo npm install crypto
sudo npm install cookie-parser
sudo npm install express-session
sudo npm install validator
sudo npm install socket.io
sudo npm install simplesmtp
